stages:
  - update

update-feeds:
  stage: update
  image: node:22
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  before_script:
    - npm install rss-parser pg
  script:
    - node scripts/update-feeds.mjs
  environment:
    name: production
  variables:
    NODE_ENV: "production"
